package views;

import controller.ControllerPrincipalView;
import java.awt.Image;
import java.awt.Toolkit;

/**
* @author Arca7 Technologies.
*/
public class PrincipalView extends javax.swing.JFrame {

    private final ControllerPrincipalView controllerPrincipalView;
    
    public PrincipalView() {
        
        initComponents();
        
        this.setExtendedState(PrincipalView.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(PrincipalView.EXIT_ON_CLOSE);
        
        controllerPrincipalView = new ControllerPrincipalView(this);
    }

    /**
     * Metodo que permitira cambiar el icono por defecto de la aplicacion.
     * @return devuelve un objecto de tipo Image.
     */
    @Override
    public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon-project.png"));
        return retValue;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorPrincipalFrame = new javax.swing.JPanel();
        contenedorViewJpanel = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SimpleHC Medium 1.0");
        setBackground(new java.awt.Color(51, 51, 255));
        setFont(new java.awt.Font("Eras Medium ITC", 3, 14)); // NOI18N
        setIconImage(getIconImage());

        ContenedorPrincipalFrame.setLayout(new java.awt.BorderLayout());

        contenedorViewJpanel.setBackground(new java.awt.Color(153, 153, 153));
        contenedorViewJpanel.setAutoscrolls(true);
        contenedorViewJpanel.setLayout(new java.awt.GridBagLayout());
        ContenedorPrincipalFrame.add(contenedorViewJpanel, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(new java.awt.Dimension(70, 45));
        jPanel1.setMinimumSize(new java.awt.Dimension(70, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(70, 45));

        btnAnterior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.setToolTipText("Ir al Anterior Formulario");
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.setEnabled(false);
        btnAnterior.setMaximumSize(new java.awt.Dimension(200, 27));
        btnAnterior.setMinimumSize(new java.awt.Dimension(200, 27));
        btnAnterior.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(btnAnterior);

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setToolTipText("Ir al Siguiente Formulario");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.setEnabled(false);
        btnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSiguiente.setMaximumSize(new java.awt.Dimension(200, 29));
        btnSiguiente.setMinimumSize(new java.awt.Dimension(200, 27));
        btnSiguiente.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(btnSiguiente);

        ContenedorPrincipalFrame.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(ContenedorPrincipalFrame, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1231, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ContenedorPrincipalFrame;
    public javax.swing.JButton btnAnterior;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JDesktopPane contenedorViewJpanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
